name: sophia_hotel

services:
  booking-service:
    container_name: booking-service
    build:
      context: ../
      target: runtime
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka
      - DATABASE_URL=jdbc:postgresql://ep-summer-sun-a1oui0l5.ap-southeast-1.pg.koyeb.app/koyebdb
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=npg_R3lfHGTMV5kA
    networks:
      - sophia_hotel

volumes:
  booking-postgres:

networks:
  sophia_hotel:
    driver: bridge